spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/MovieTicket
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  project:
    poster: posters/

  base:
    url: "http//localhost:8080"

# Liquibase set-up
  liquibase:
    change-log: classpath:db/changelog/master/db.changelog-master.yaml
    enabled: true

  logging:
    level:
      root: DEBUG

